### PR TITLE
Add delete lesson command parser test

### LINKED ISSUE #231: Add test cases for DeleteLessonCommandParser

### LINKED ISSUE #239: Incorrect error message for delete command
When in schedule state, typing the command `delete` gives the wrong error message. It should indicate deleteLesson, not person
image

### PR DESCRIPTION
**Pull request by elaineshijie**
1. Add tests for delete lesson command parser Fixes #231 
2. Incorrect delete lesson message displayed, made the changes accordingly Fixes #239

### CODE REVIEW

**Review by richiehx — APPROVED** [review]
LGTM! Can try adding a test for the equals method in DeleteLessonCommand.

**Comment by pzl111** [comment]
Could you take a look at issue #239 ? its related to delete lesson command parser, where there is an incorrect error message

**Review by pzl111 — CHANGES_REQUESTED** [review]
Could you take a look at issue #239 ? its related to delete lesson command parser, where there is an incorrect error message

**Comment by elaineshijie** [comment]
@pzl111 
Already made the changes in this pr, updated pr comment to include #239, thank you!
Refer to line 22 of deletelessoncommandparser

**Comment by pzl111** [comment]
> @pzl111 Already made the changes in this pr, updated pr comment to include #239, thank you! Refer to line 22 of deletelessoncommandparser

I got that issue my testing on ur PR code though

**Review by pzl111 — APPROVED** [review]
LGTM!

**Pull request merged**
