### PR TITLE
Add Structure for Task List

### LINKED ISSUE #84: Create TaskList for Lesson

### LINKED ISSUE #90: Set current showing Person and Lesson in Model

### PR DESCRIPTION
**Pull request by richiehx**
Fixes #84 
Fixes #90 

Changelog:
1. Added current Showing Person and Lesson in ModelManager.
2. Fix typos in Lesson class
3. Added TaskList and Task classes
4. Added taskListView in LessonDetailListPanel
5. Created TaskCard to display the tasks
6. Modify Lesson constructor to add TaskList
7. Fixed merge conflicts with #85 by adding TaskList to the new Lesson constructors
8. Added placeholder serialize and deserialize methods for TaskList in the Lesson class (TODO)

### CODE REVIEW

**Comment by pzl111** [comment]
LGTM but can you add some test cases to pass codecov?

**Comment by richiehx** [comment]
I was prioritising the implementation of the complete features before the end of v1.3 as there will be a feature freeze in 1.4.
I will add more tests later for code coverage when I have more time.

as referenced from the issue in the forums, testing can be delayed to v1.4 if we need to implement the features first:
https://www.github.com/nus-cs2103-AY2324S1/forum/issues/281

**Review by yiwen101 — APPROVED** [review]
LGTM

**Review by yiwen101 — CHANGES_REQUESTED** [review]
Emm, thank you for pointing us to this, it is certainly good news and to the joy of my heart. To further play safe, I just made a follow up query to that forum equation as there is still some ambiguity in the current answer in the "https://www.github.com/nus-cs2103-AY2324S1/forum/issues/281" as the response is open to interpretation.Let us merge this only after getting concrete response from prof, shall we?  Delaying merging for one day should not harm productivity too much, as could still work on changes locally.

**Review by yiwen101 — APPROVED** [review]

**Pull request merged**
