### PR TITLE
Branch delete command

### PR DESCRIPTION
**Pull request by yiwen101**
There are two major changes:
Firstly, added the delete lesson command. I added the parsers, integrate them to the address book parser and refractor the original delete command to deletePerson command. Important files for this change are "DeletePersonCommand" , "DeletePersonCommandParser", "DeleteLessonCommand", ""DeleteLessonCommandParser".

Secondly, I modify the address book parser such that it could interpret "add, edit, delete" as "addLesson", "addPerson" .... based on the "State" variable in model. It is assumed that the "State" is either "PERSON" or "SCHEDULE", not "NONE". Important file for this change is "AddressbookParser"

The rest are ripple effect due to the update, like updating test case, check style, and renaming files.

### CODE REVIEW

**Comment by yiwen101** [comment]
Fix #122 #123

**Comment by elaineshijie** [comment]
Seems like edit command is not working as intended
Screenshot 2023-10-31 at 5 06 53 PM

editLesson 1 -start 13:20 works
Screenshot 2023-10-31 at 5 07 27 PM

Behaviour of lesson commands: can only add one subject
[editLesson -subject ENGLISH -subject MATHEMATICS] gives:
Screenshot 2023-10-31 at 5 11 08 PM
Good to change error message to: Please specify only one subject per lesson

**Comment by elaineshijie** [comment]
okay recent commit works as intended

**Comment by yiwen101** [comment]
> Seems like edit command is not working as intended Screenshot 2023-10-31 at 5 06 53 PM
> 
> editLesson 1 -start 13:20 works Screenshot 2023-10-31 at 5 07 27 PM
> 
> Behaviour of lesson commands: can only add one subject [editLesson -subject ENGLISH -subject MATHEMATICS] gives: Screenshot 2023-10-31 at 5 11 08 PM Good to change error message to: Please specify only one subject per lesson

Thank your for the response.
Yeah, the first bug is valid. I just made a new commit to fix it.
The second is that you forget to put index after your editLesson command so the error message is not wrong. It will also detect for duplicate flags by the way.

**Review by elaineshijie — APPROVED** [review]
LGTM!

**Pull request merged**
